import Head from "next/head";
import { Fragment, useState } from "react";
import { InputGroup, FormControl, Button } from "react-bootstrap";
import UserCard from "../components/UserCard";

import { useDispatch, useSelector } from "react-redux";
import { getUser } from "../redux/actions";

import styles from "../styles/index.module.css";

export default function Home() {
  const dispatch = useDispatch();

  const [searchInput, setSearchInput] = useState("");
  const handleChange = (e) => setSearchInput(e.target.value);

  const handleClick = async () => {
    dispatch(await getUser(searchInput));
  };

  const user = useSelector((state) => state.userReducer.user);

  return (
    <Fragment>
      <Head>
        <title>Github Fetcher | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <InputGroup className="mb-3">
          <FormControl
            placeholder="Enter username here"
            value={searchInput}
            onChange={handleChange}
          />
        </InputGroup>
        <Button
          className={styles.searchButton}
          variant="dark"
          onClick={handleClick}
        >
          Search
        </Button>

        <UserCard
          key={user.id}
          userName={user.login}
          userImage={user.avatar_url}
        />
      </div>
    </Fragment>
  );
}
